# .github/workflows/ci-cd.yml

name: Deploy Next.js to Server

on:
  push:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      
      # --- 修正之处 ---
      # 在 GitHub Actions 环境中，Nix 配置文件位于项目根目录，所以使用 "."
      - name: Install Dependencies
        run: nix develop . --command pnpm install
      - name: Build Project
        run: nix develop . --command pnpm run build

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # --- 您需要确认和修改的部分 ---
            
            # 1. 确认服务器上的项目路径是否正确
            cd /home/bytedream/react-docs
            
            echo "Pulling latest code from master branch..."
            git pull origin master
            
            # 2. 确认服务器上的 Nix 环境路径是否正确
            echo "Installing dependencies..."
            /nix/var/nix/profiles/default/bin/nix develop /home/bytedream/dev --command pnpm install
            
            echo "Building application for production..."
            /nix/var/nix/profiles/default/bin/nix develop /home/bytedream/dev --command pnpm run build
            
            # 3. 将 'your-service-name.service' 修改为您的真实服务名
            echo "Restarting systemd service..."
            sudo systemctl restart csgo-cms.service
            
            echo "Deployment successful!"
